{% set name = "dash-extensions" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_extensions-{{ version }}.tar.gz
  sha256: 5771d293aa07160a5118d3a69d78b5fd6a574c842d3435248c23636a23ae68a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - dash >=3.0.0
    - more-itertools >=10.6.0
    - jsbeautifier >=1.15.4
    - flask-caching >=2.3.1
    - dataclass-wizard >=0.35.0
    - pydantic >=2.10.6

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - dash_extensions
  commands:
    - pip check

about:
  home: https://dash-extensions.com
  summary: Extensions for Plotly Dash.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - whophil
    - mitchellwood
    - fhoehle
    - '0xbe7a'
