{% set name = "dash-extensions" %}
{% set version = "1.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_extensions-{{ version }}.tar.gz
  sha256: 38fc6127df57006ea11a7d0066ab361fd6baefeeef5b58e58cdfe88440070f36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1

  run:
    - python >=3.8,<4.0
    - dash >=2.9.3
    - flask-caching =2.0.2
    - jsbeautifier >=1.14.3,<2
    - more-itertools >=9.0.0,<10.0.0
    - dataclass-wizard >=0.22.0,<0.23.0
  run_constrained:
    - dash-mantine-components >=0.11.1,<0.12.0


test:
  imports:
    - dash_extensions
  # failing due to dash missing dash-core-components, dash-html-components and dash-table 
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://dash-extensions.com
  summary: Extensions for Plotly Dash.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - whophil
    - mitchellwood
    - fhoehle
    - '0xbe7a'
